name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "bin/*"
      - ".github/workflows/*"
  pull_request:
    paths:
      - "bin/*"
      - ".github/workflows/*"

jobs:
  plugin_test:
    permissions:
      contents: read
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    env:
      PYTHON_TO_NOT_USE: "3.12"
    steps:
      - name: Install extras
        if: ${{ matrix.os == 'macos-latest'}}
        run: |
          sudo rm -rf "/Library/Frameworks/Python.framework/Versions/${PYTHON_TO_NOT_USE}"
          sudo rm -rf "/Applications/Python ${PYTHON_TO_NOT_USE}"
          sudo find /usr/local/bin -lname '../../../Library/Frameworks/Python.framework/Versions/${PYTHON_TO_NOT_USE}/*' -delete
          brew link --force python@3.11
          hash -r
          python3 --version

      - uses: asdf-vm/actions/plugin-test@05e0d2ed97b598bfce82fd30daf324ae0c4570e6 # v3.0.2
        with:
          command: az version
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
