name: CI
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "bin/*"
      - ".github/workflows/*"
  push:
    paths:
      - "bin/*"
      - ".github/workflows/*"
  schedule:
    - cron: "0 0 * * *"

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install extras
        if: ${{ matrix.os == 'macos-latest'}}
        run: |
          brew install openssl readline sqlite3 xz zlib tcl-tk

      - uses: asdf-vm/actions/plugin-test@v3
        with:
          command: az version
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
