name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "bin/*"
      - ".github/workflows/*"
  pull_request:
    paths:
      - "bin/*"
      - ".github/workflows/*"

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install extras
        if: ${{ matrix.os == 'macos-latest'}}
        run: |
          brew uninstall --ignore-dependencies python@3.12
          brew unlink python3.12
          brew unlink python@3.11 && brew link --force python@3.11
          hash -r
          python3 --version

      - uses: asdf-vm/actions/plugin-test@v3
        with:
          command: az version
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
