name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "bin/*"
      - ".github/workflows/*"
  pull_request:
    paths:
      - "bin/*"
      - ".github/workflows/*"

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-11
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install extras
        if: ${{ matrix.os == 'macos-11'}}
        run: |
          brew install openssl readline sqlite3 xz zlib tcl-tk

      - uses: asdf-vm/actions/plugin-test@v3
        with:
          command: az version
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
